### PR TITLE
Added new task to delete all archived pages

### PR DESCRIPTION
**Pull request by yorikw**
-Added new task to delete all archived pages
-Combined logic from your _getAllVersionedDataClasses() and
https://github.com/silverstripe/silverstripe-versioned-admin/blob/2/src/ArchiveAdmin.php#L131

image

### CODE REVIEW

**Comment by axllent** [comment]
Thanks - that looks much better (edited the correct file) :-) I will look into this tonight or tomorrow depending on time.

**Comment by axllent** [comment]
Thanks @yorikw. There are a few things I am going to change, for example `_getAllVersionedDataClasses()` returns all versioned classes and not just SiteTree, so I will expand it to all DataObjects and not just pages. I appreciate the effort!

**Comment by axllent** [comment]
I've just released a new version with the changes :+1:

**Comment by yorikw** [comment]
That's great! I found this module to be very helpful, and that was the reason I added support for archived pages deletion, so it has solved all my db cleanup related problems. Thanks for your time!

**Pull request merged**
