### PR TITLE
Added task to delete all archived pages

### PR DESCRIPTION
**Pull request by yorikw**
-Added new task to delete all archived pages
-Combined logic from your _getAllVersionedDataClasses() and 
https://github.com/silverstripe/silverstripe-versioned-admin/blob/2/src/ArchiveAdmin.php#L131

### CODE REVIEW

**Comment by axllent** [comment]
@yorikw I think you have made a mistake here... You appear to have replaced `src/VersionTruncator.php` with what appears to be your updated version of `src/Tasks/TruncateVersionsTask.php`.

**Comment by yorikw** [comment]
Yes, but I didn't replace it, I just add the new task to your existing page.

image

**Comment by yorikw** [comment]
Hmm, I see some of those changes, which were probably added by Silverstripe. I'll try to fix them soon. Thanks

**Comment by yorikw** [comment]
Ah, I know what happened, I pulled the code from the task file here
https://github.com/axllent/silverstripe-version-truncator/blob/master/src/Tasks/TruncateVersionsTask.php
I'll kill this PR and will open the new one.
Thanks

**Comment by yorikw** [comment]
Code conflict. Will open a new PR

**Pull request closed without merging**
